### ISSUE TITLE
Warning (2): Invalid argument supplied for foreach() [APP/Plugin/Media/Model/Behavior/GeneratorBehavior.php, line 162]

### ISSUE THREAD

**Issue by jonandress** [VolantisDev/CakePHP-Media-Plugin#26]
I couldn't get the Generator behavior to work, and I believe it is in part due to a typo on line 160.

$filter = Configure::read('Media.filter.' . Mime_Type::guessName($file));;

Configure::read('Media.filter.') is empty.  

Configure::read('Media.filter') returns the expected list of filters.

I changed it to:

```
    $filter = Configure::read('Media.filter');
    $filter = $filter['default'][Mime_Type::guessName($file)];
```

And got it to write the images as expected.  Perhaps I have an implementation error?

**Comment by ReplicaObscura** [comment]
Hello,

I don't believe there actually is a typo there (It's not trying to read 'Media.filter.', but rather 'Media.filter.' concatenated with the MIME type of the file).

However it looks like it hasn't been updated for my new approach to filters which adds an extra dimension to the array. (The 'default' key, or any other named key, one level above the MIME type, as you have in your corrected code).

Rather than two lines, you probably could have just used Configure::read('Media.filter.default.'.Mime_Type::guessName($file)) but I haven't tested that to be sure.

Ultimately, I think the GeneratorBehavior should be able to use other filter sets besides just 'default' however. Either through configuration, or potentially by trying to determine automatically. For instance, I usually key mine based on model, so I might have 'default', 'User', 'Company', etc. each with their own settings for each MIME type.

I think simply trying to use the model name as the key, or 'default' if that doesn't exist, would be sufficient, but I'll need to think about that a bit to see if it's flexible enough.

Thanks very much for reporting this!

**Comment by ndm2** [comment]
This should not be relevant anymore, the filter retrieval changed, and since #41 there is no `default` key anymore.

**Comment by ReplicaObscura** [comment]
Thanks for following up on this @ndm2
