### ISSUE TITLE
Image is not uploaded to transfer folder

### ISSUE THREAD

**Issue by PHANTOMIAS** [VolantisDev/CakePHP-Media-Plugin#4]
I have CakePHP 2.0.2 and the latest version of yours CakePHP Media Plugin.

I uploaded all files to 'app/Plugin/media' and I created these directory by myself:
- app/Plugin/media/filter/
- app/Plugin/media/static/
- app/Plugin/media/transfer/

Each folder has these subfolders:
-- aud/
-- doc/
-- gen/
-- img/
-- vid/

In 'app/Config/core.php' I added this line
require_once(APP.'Plugin'.DS.'media'.DS.'Config'.DS.'core.php');
in the last line of this core.php file.

And this line in 'app/Config/bootstrap.php':
CakePlugin::load('Media');

In my 'app/View/Regions/add.ctp':

<?php
echo $this->Form->create('Region', array('type' => 'file'));
echo $this->Form->input('name');
echo $this->Form->input('file', array('type' => 'file'));
echo $this->Form->end('Add Region');
?>

In the Model 'app/Model/Region.php', I added this lne:
var $actsAs = array('Media.Transfer');

In 'app/Controller/RegionsController.php':

public function add() {
    if ($this->request->is('post')) {
        debug($this->request->data);
    }
}

The data has all the image data:

Array
(
    [Region] => Array
        (
            [name] => ddd
            [file] => Array
                (
                    [name] => test.jpg
                    [type] => image/jpeg
                    [tmp_name] => /var/www/test/phptmp/phpNGHHYm
                    [error] => 0
                    [size] => 51827
                )
        )
)

Now I read in the tutorial file which is located under 'app/Plugin/media/docs/TUTORIAL':

If you now go and repeat submitting the file via the add form, this
time the file should end up being stored below webroot/media/transfer
in img/clipboard.jpg.

But in my case, there is no test.jpg image in this folder, and there is no error message. So what's the problem?
I also added .htaccess files with content 
Order deny,allow
Deny from all
but that should not be the problem.

Anyone an idea?

**Comment by PHANTOMIAS** [comment]
The tmp_name exists while uploading the file: /var/www/test/phptmp/phpNGHHYm
After the upload is finished, the file phpNGHHYm disappears in this tmp folder.

I searched for 'move_uploaded_file' and I found this file 'app/Plugin/media/Model/Behavior/TransferBehavior.php' and the method 'transfer', but this method is not called, because I did a 
echo "test";die();

**Comment by ReplicaObscura** [comment]
Thanks for bringing this to my attention. I haven't had much time recently to work on my PHP projects--I am currently using this plugin in a website I've been developing, but that site is still running a RC of CakePHP 2.0 so it's possible that something has changed since then that caused this issue.

The other possibility is some configuration or server issue preventing the file from being moved to its final destination--I'll update my CakePHP and try to test the script again and see if I can come up with a solution ASAP for you.

Thanks again, and sorry for the delay!

**Comment by PHANTOMIAS** [comment]
Okay, thank you for your reply. I will wait for answer.

**Comment by ghost** [comment]
PHANTOMIAS, try the new installation guide and see if it will work for you. :)

**Comment by PHANTOMIAS** [comment]
aeolu, thanks a lot, I see that there were fixes in this github repository.
But I can not find the new installation guide. Can you please tell me where to find?

**Comment by ghost** [comment]
The readme. :) I think bmcclure is already using my Readme markdown though follow the readme from my fork since I forgot to add some key points in the markdown when he merged my pull request. :)

**Comment by ReplicaObscura** [comment]
@PHANTOMIAS Let me know if the installation guide helps you or if you have additional issues.

@aeolu Thanks very much for the assistance, and the documentation! I'll be happy to continue to merge any and all pull requests that look good to me, so don't hesitate to continue submitting requests for the updates you make to the documentation.

**Comment by ReplicaObscura** [comment]
@aeolu I just noticed you already did submit the updated documentation :) Thanks, and it has been accepted!

**Comment by PHANTOMIAS** [comment]
I downloaded the latest vesion and followed the instructions of the readme.
I have to change
require_once APP . 'Plugin/Media/config/core.php';
to 
require_once APP . 'Plugin/Media/Config/core.php';
because the folder "config" is written with a capital C.

But unfortunately, same effect. I see while uploading the file in my phptmp folder, with the debug message, I see the details of the file (everything okay), but no file in webroot/transfer/img folder.

So, I do not have any idea what's wrong here. I do not have the database, I only want to upload this image in a first step. But there are no error messages, that it is not possible to move the picture, etc.

I think the method 'transfer' in the TransferBehavior.php has to be called? But it does not... Also 'public function beforeSave($Model)'
 is not called. So it does not trigger anything. But wait, do I have to perform a save operation? If I do this, it tries to save the "file" into my database but there is no column "file" in this database table.

**Comment by PHANTOMIAS** [comment]
I created a database column, and so it works. So it was my mistake...
But I thought, that I do not need a database table / column?

**Comment by ReplicaObscura** [comment]
@PHANTOMIAS I was just coming on here to respond to your previous message and tell you to try configuring a DB table for it, but it looks like you've done that already :)

You don't need to store the file itself in the database, you generally store the pathname and filename (and optionally some other meta data) in the database table which points to the real location of the file. Additionally, you can use the schemas that are included with the plugin to help automate the process so that you don't need to make any manual changes to your database at all. That way, you'd just have a single 'attachments' table which links media on the filesystem to records in other tables.

I used 'Config' as the folder name because the particular pre-release version of CakePHP 2.0 I was coding it for capitalized it the same way. I'm fine with switching the capitalization to whichever way is currently considered standard, however.

Thanks a lot for reporting this and following up with the workaround you used. Out of curiosity, would you mind sharing some details about your particular use case of wanting to upload media without associating it to any table? I've never run into a situation personally where I've wanted to upload media without associating it to any model record, so I would be interested in learning more about that scenario and potentially coding to allow for it in the future.

Thanks again!

Ben

**Comment by PHANTOMIAS** [comment]
In the end, I need this for my scenario:
Upload an image and I do not want that images with the same name will be overwritten, so I think I will need to change the filename so I will add a timestamp. This name of the file, I need to store into the database.
Additionally, I will need a smaller version of this image, I need to resize it so that the larger size of width or height should be resized to 100px (proportionally). For that I do not need a database column, because the name should be the same like the original, but with a suffix "_small".

**Comment by ReplicaObscura** [comment]
Oh ok, in that case that should already be possible. I can try to help you configure that to work, as I'm doing something slightly similar with my newest portfolio site.

Do images have a one-to-one relationship with the database records they're being associated with, or can each record have more than one image?

**Comment by PHANTOMIAS** [comment]
It would be great, if you can help me. Each record will have one image.

**Comment by ghost** [comment]
@PHANTOMIAS don't change the config to Config, unless you move the core.php file to the Config folder.

Try using the PHPThumb plugin that comes along with it to store a resized version of the Plugin. Hope this helps. :)

**Comment by PHANTOMIAS** [comment]
I have a problem using the plugin: I upload an image, works fine, it is written into the database. Deleting the record, the image is also delted on the file system. But, uploading a picture named "test1.png", the picture is uploaded, but the editing it and upload a picture named "test2.gif", both files are still present in the file system.
So, what I want to have: If a picture is changed by uploading another one for this record which replace it in the database, I also want that the old picture is deleted in the file system.
How can this be achieved?

**Comment by ghost** [comment]
Could you show us your edit.ctp?

**Comment by PHANTOMIAS** [comment]
My edit.ctp, okay, here it is:

<?php
echo $this->Form->create('Test', array('action' => 'edit', 'type' => 'file'));
echo $this->Form->input('name');
echo $this->Form->input('file', array('type' => 'file'));
echo $this->Form->input('dirname', array('type'=>'hidden'));
echo $this->Form->input('basename', array('type'=>'hidden'));
echo $this->Form->input('id', array('type' => 'hidden'));
echo $this->Form->end('Change Submit');
?>

**Comment by lawrence615** [comment]
Hi,

I am trying to use this plugin to upload pictures in a website that am building but am encountering some challenges.

First off when i execute the command "cake Media.Media init", this is what happens

![1](https://f.cloud.github.com/assets/3224157/85604/8e0cb910-646c-11e2-8585-7e857a02f475.png)

The image above shows that the transfer directory is been created outside the webroot directory. When I upload images there been saved in that directory.  

Now  the problem comes  when I try to display, the view does not get the image in the path specified as it tends to check in webroot folder. It does not find the transfer directory and thus displays nothing.

Please help

**Comment by ReplicaObscura** [comment]
@lawrence615:

The transfer directory shouldn't be used for displaying images--once the upload completes successfully, they should be in your app\webroot\media\static, or app\webroot\media\filter directory (if you are modifying them with filters). Can you post your config for Media?

**Comment by AppSynergy** [comment]
Hi all, 

I just downloaded and installed this plugin.  (have used previously approx. July last year)
I was also puzzled by the transfer dir appearing in app/Media instead of app/webroot/media like it was last time.

Surely Config/bootstrap L107 should be:

``` php
define('MEDIA_TRANSFER', MEDIA . 'transfer' . DS);
```

right?

Making that change and doing init again, I find that the uploaded image goes to the transfer directory in the right place  -  but nothing gets created in static (or filter, but I haven't tried filters yet).

What else is going on here?

**Comment by ReplicaObscura** [comment]
The change @AppSynergy suggests is in the current codebase now. It's hard to say why filters weren't working, but I would venture a guess that they should be working properly now after the recent changes. If not, please do re-open.

**Comment by vnandan** [comment]
I have followed all steps in README, docs and the ones above mentioned including creating table in DB. I receive the image data in $this->request but dont receive in the folder.

**Comment by ndm2** [comment]
@vnandan Nobody will be able to troubleshoot this without more information, like do the folders have the proper rights set, is there any validation involved, are you in debug mode, do you receive any errors, what exactly does the data received look like, etc etc...

**Comment by vnandan** [comment]
OK. here goes,
1. all folders have the required permission.
2. no validation involved. I am still trying to get the basic example running.
3. debug mode ,2
4. no errors.
5. the received data is 
array(
    'Attachment' => array(
        'photo' => array(
            'name' => 'mypic.jpg',
            'type' => 'image/jpeg',
            'tmp_name' => 'C:\xampp\tmp\phpBB67.tmp',
            'error' => (int) 0,
            'size' => (int) 27666
        )
    )
)
The details of the prob. are similar to @PHANTOMIAS  except that creating table didn't solve the problem for me.

Running 
: cakePHP 2.6.0 (stable)

**Comment by ndm2** [comment]
@vnandan  The fieldname must be `file`, not `photo`.

**Comment by vnandan** [comment]
Corrected that. Didn't work. Debugged data is 

array(
    'Attachment' => array(
        'dirname' => '',
        'basename' => '',
        'checksum' => '',
        'file' => array(
            'name' => 'mypic.jpg',
            'type' => 'image/jpeg',
            'tmp_name' => 'C:\xampp\tmp\php377E.tmp',
            'error' => (int) 0,
            'size' => (int) 27666
        )
    )
)

**Comment by ndm2** [comment]
@vnandan  Please show your behavior config, model associations, and controller action code.

ps, please format your your code readibly as actual code: https://guides.github.com/features/mastering-markdown/#examples

**Comment by vnandan** [comment]
I have put up a fresh install of cake and installed this plugin. Just to keep things simple. Just one model - Photo.
The result is still the same. The behavior config is default with no changes. And no code in controller  action add() except:

``` php
debug($this->request->data);
```

The only deviation from the docs is in the addition of 

``` php
require APP . 'Plugin' . DS . 'Media' . DS . 'Config' . DS . 'bootstrap.php';
```

instead of 

``` php
require APP . 'Plugin' . DS . 'Media' . DS . 'Config' . DS . 'core.php';
```

Also I have created the folders manually:
-app
- webroot
  - media
    - transfer
      - img
    - static
      - img
    - filter
      - img

**Comment by ndm2** [comment]
@vnandan How do you expect anything to happen when there is no code in the controller action other than a call to `debug()`?

Also note that there is no need to include the bootstrap file manually (also there is no `core.php`, these old docs are pretty outdated), it's going to happen automatically by defining `'bootstrap' => true` in the `CakePlugin::load()` call.

```
CakePlugin::load('Media', array('bootstrap' => true));
```

**Comment by vnandan** [comment]
As it might be apparent, I am a newbie to Cake behaviors. The docs/tutorial (although outdated) say exactly that: 

> When you now go and inspect $this->data within in your Posts controller's
> add action, you should see something like this after you tried 
> uploading a file. The file gets submitted but will discarded as it's
> currently not handled by any code.
> 
> ``` php
> {{{
> Array 
> ( 
>     [Post] => Array 
>     ( 
>     [title] => Demo 
>     [file] => Array 
>         ( 
>             [name] => clipboard.jpg 
>             [type] => image/jpeg 
>             [tmp_name] => /private/var/tmp/php4zN7BY 
>             [error] => 0 
>             [size] => 32405 
>         ) 
>     ) 
> ) 
> }}}
> ```
> 
> Until now nearly everything you did wasn't really taking advantage of
> the plugin. We'll change that now by editing the post model in 
> models/posts.php by adding the transfer behavior to the actsAs property.

``` php
{{{
class Post extends AppModel {
    var $actsAs = array('Media.Transfer');
}
}}}
```

> If you now go and repeat submitting the file via the add form, this
> time the file should end up being stored below webroot/media/transfer
> in img/clipboard.jpg.

It suggests that adding the `$actsAs` to Model would do the trick.
I expected that the file's upload to folder would be done automagically, if not the `save()` Not sure if i'm mistaken. Could you point in the right direction?

**Comment by ndm2** [comment]
@vnandan The docs suck, and they require knowledge about how behaviors work. Maybe someone should update them, it's most likely not going to be me though :trollface: 

Anyways, nothing is going to happen unless you invoke the models `save()` method, this will trigger the behaviors `beforeValidate()`/`beforeSave()` callbacks, which is where the magic happens.

**Comment by vnandan** [comment]
_Some_ progress. 
With `$this->Mediafile->save($this->request->data['Mediafiles']);` got the DB entry made. The files is not moving to the folder though :/

I played around with the TransferBehaviour.php and did a `echo $result` where 
`$result = move_uploaded_file($temporary['file'], $destination['file']);`

The result was `1`. But the file has not moved. Any ideas?
PS: Checked the folder permissions.

**Comment by ndm2** [comment]
Try debugging the values passed to `move_uploaded_file()`, maybe the files aren't going to where you'd expect them to go.

**Comment by vnandan** [comment]
Got it!
The permissions for creating files were inheriting from 3 generations up.

Thanks @ndm2 .
