### ISSUE TITLE
Should MediaHelper::embed()/embedAsObject() support URLs additionally to file paths?

### ISSUE THREAD

**Issue by ndm2** [VolantisDev/CakePHP-Media-Plugin#44]
So while trying to implement #42, I've noticed that it looks like `MediaHelper::embed()` and `MediaHelper::embedAsObject()` were somehow expected to not only take file paths, but also (absolute) URLs.

While the parameter documentation only speaks of absolute or relative file paths, `MediaHelper::_sources()` actually checks whether the passed path is a URL (let's ignore for a moment that the parameter order is wrong, of course the haystack needs to come first):

``` php
if (strpos('://', $path) !== false) {
    $file = parse_url($url, PHP_URL_PATH);
}
```

https://github.com/bmcclure/CakePHP-Media-Plugin/blob/b17fc6be07325b93350cad8ccd291acca5b558cc/View/Helper/MediaHelper.php#L528

However, this won't work, first of all the code never reaches the point where the path is tested for being an absolute URL, as it will fail here first:

``` php
if (!$url = $this->url($path, $full)) {
    return false;
}
```

https://github.com/bmcclure/CakePHP-Media-Plugin/blob/b17fc6be07325b93350cad8ccd291acca5b558cc/View/Helper/MediaHelper.php#L525

But let's assume something magic :sparkles:  happens and the URL would make it through this check and the wrongly called `strpos`, and both `$path` and `$url` would actually contain an URL like `http://example.com/media/static/img/image-png.png`.

It would then extract the `/media/static/img/image-png.png` part and use this as the file path, and again, it would fail, as it would look for `/media/static/img/image-png.png` in the filesystem, and this is most likely not be the absolute path to the file (additionally this might trigger an `open_basedir` restriction error).

So now I'm a little bit lost here, not just because it doesn't work and it's pretty hard to tell how this might have been _supposed_ to work, but also because I'm wondering whether `MediaHelper::embed()/embedAsObject()` supporting URLs would be a good idea at all?

**Comment by ReplicaObscura** [comment]
That's an excellent question, I think I may have glossed over that part when working on updating the plugin for Cake 2.x, and I don't believe I've ever tried or had a reason to use an absolute URL there.

I can't think of a very good reason for using an absolute URL if the media is actually contained in the current site on the local filesystem, which seems to be the only way it CAN work since it tries to create a local absolute path unless I'm misunderstanding that portion.

But that aside, my initial thought with why it accepted URLs was that you could provide an absolute URL for a media path and that it would either:
(a) directly output the media at the absolute URL, or
(b) in the case of filtering, download a copy of the media and filter it as if it were a local file, then output the filtered file like any other.

However I never fully thought that through and just sort of left the code as-is. Unless anyone else chimes in with other suggestions, I'm currently fine either way if you think it best that we either:
1. Just remove absolute URL support from embed() and embedAsObject() (or just fix _sources() to not support URLs at all if that's all it's used for), or
2. Fix and expand absolute URL support so that it can take any URL and either directly output media with that as the src, or locally filter the remote file and output that version.

That's my thought, but I'm open to any other ideas here as well.

**Comment by ndm2** [comment]
I'm wracking my brain about this for quite some time now, and I tend to think that the helper should only work with local file paths. I see two reasons for this:
1. The Media helper seems pretty much useless without the analysis and path expanding functionality, so for basic pointing to remote URLs one could use the Html helper instead.
2. The Transfer behavior is already capable of transferring remote files, so it's relatively simple to handle inclusion of remote files in the Model layer and supply the View with appropriate local paths.

In any way URL support would be a feature addition I guess, as it seems that the helper was never capable of handling URLs, the code executes [the same logic](https://github.com/davidpersson/media/blob/5af3e2a6e2e85d985db222b058f0fef952b0bdf1/views/helpers/media.php#L551) ever since it was first implemented in @davidpersson's original codebase.

**Comment by ReplicaObscura** [comment]
I tend to agree with that logic. You lose most of what Media is doing if you're just referencing remote files, meaning the only reason to implement might be for consistency's sake of being able to use the same helper for all media (and that's probably not a good enough reason).

I'd say we could just remove the broken URL support and revisit this if it ever comes up again?

**Comment by ndm2** [comment]
I would agree to that, just remove it for now until someone comes up with an idea how URL support could be implemented in an useful manner.
