### ISSUE TITLE
Travis integration and backwards compatibility

### ISSUE THREAD

**Issue by ndm2** [VolantisDev/CakePHP-Media-Plugin#47]
I've noticed that Travis is enabled for this repository, but it's not working as it's missing an appropriate configuration.

I've played with it a little bit and figured a configuration that works with all the latest CakePHP 2.x.x builds:

https://github.com/ndm2/CakePHP-Media-Plugin/blob/f6257c9eff501c0e29545aadf44afd26f61b3c1f/.travis.yml
https://travis-ci.org/ndm2/CakePHP-Media-Plugin/builds/13637928

Though it requires suppressing `E_NOTICE` for 2.0.x builds as of PHP 5.4, since some of the overwritten method signatures have changed (haven't yet figured a proper way to apply suppression only to the builds using PHP => 5.4).

I guess it's debatable whether trying to keep a branch compatible over that many versions is a good thing, so I thought I'd bring this up for discussion.

Personally I think backwards compatibility is generally nice to have, especially for legacy applications, and as long as it doesn't require too much jumping through hoops, I would prefer this over maintaining multiple branches.

**Comment by ReplicaObscura** [comment]
Thanks very much for looking into this!

I completely agree about keeping backwards compatibility as long as it's not too difficult to do so (and it sounds like it's not in this case), and as long as the plugin is otherwise compatible with 2.0.x (Haven't tested it myself in a while but I would assume it is).

I would also rather this than have to maintain multiple branches, to keep it simple both for contributors and users of the plugin.
